package com.example.jake.andromedia;

import java.util.Collections;

public class QuizLibrary {

    //First array holds all questions in Topic 1
    private String mQuestions1[] = {

            "Q1. What popular OS is Android based on?",
            "Q2. What famous company is known for its contributions to the Android OS?",
            "Q3. What language is Android programming based around?",
            "Q4. What operating systems are you able to develop android applications on?",
            "Q5. How many Layers is the Android OS split into?",
            "Q6. What library is specific to OpenGLs rendering API?",
            "Q7.  What does DVM stand for?",
            "Q8. What does the Activity Manager do?",
            "Q9. What is the Applications layer?",
            "Q10. What version of Linux is on the bottom layer?"
    };

    //Second array of questions
    private String mQuestions2[] = {

            "Q1. What four components can be used within an Android application?",
            "Q2. How many components are used within an Android application?",
            "Q3. What is an activity?",
            "Q4. What does the Services component do?",
            "Q5. What is a Service component used for?",
            "Q6. What does a Content Provider do?",
            "Q7. What are views?",
            "Q8. What are fragments?",
            "Q9. What is the manifest file?",
            "Q10. What is a Broadcast Receiver?"
    };

    //Third array of questions
    private String mQuestions3[] = {

            "Q1. What is the Java directory for?",
            "Q2. What is the purpose of the Manifest.xml file?",
            "Q3. What is the MainActivity.java file?",
            "Q4. What is the String file?",
            "Q5. What is a Layout file?",
            "Q6. Where is the directory for XML files?",
            "Q7. Where is the directory for app interface files?",
            "Q8. Where is the directory for drawable object files?",
            "Q9. What is the TextView value for in Android?",
            "Q10. What does the command @string/ do?"
    };

    //Fourth array of questions
    private String mQuestions4[] = {

            "Q1. What is the resource file anim/ for?",
            "Q2. What is the resource file drawable/ for? ",
            "Q3. What is the resource file layout/ for?",
            "Q4. What is the resource file color/ for?",
            "Q5. Why should you provide alternative resources?",
            "Q6. What ways can you access resource files?",
            "Q7. What is the R class generated by Android on compilation?",
            "Q8. What is the values/ directory?",
            "Q9. What is the arrays.xml file?",
            "Q10. What is the styles.xml file?"
    };

    //Fifth array of questions
    private String mQuestions5[] = {

            "Q1. How does Android initiate its program?",
            "Q2. What does onStart() do?",
            "Q3. What does onResume do?",
            "Q4. How many callback methods are their?",
            "Q5. What does onStop() do?",
            "Q6. What does onDestroy() do?",
            "Q7. What does onRestart() do?",
            "Q8. Why must you include the MAIN action and LAUNCHER category in the AndroidManifest?",
            "Q9. What does the setContentView(R.layout.activity_main) do?",
            "Q10. What does the Log.d() method do?"
    };
    //First array holds all possible answers for questions in Topic 1
    private String mChoices1[][] = {

            {"Windows OS", "iOS"},
            {"Microsoft", "Samsung"},
            {"Java", "C/C++"},
            {"Windows & Max", "Windows"},
            {"3", "5"},
            {"android.database", "android.webkit"},
            {"Davlik Vending Machine", "Debugging Virtual Machine"},
            {"Provides access to non-code resources such as strings, colours and layouts", "Allows the user to find notifications about current activities"},
            {"Stores libraries for external applications", "Can be used to store multiple application types"},
            {"2.5", "3.7"}
    };

    //Seoond array holds all possible answers for questions in Topic 2
    private String mChoices2[][] = {

            {"Services, DVM, Layouts & Content Providers", "Activities, Services, Broadcast Receivers & Content Providers"},
            {"6", "4"},
            {"A task scheduled on the CPU", "A process running in the background"},
            {"Provide a list of helpful libraries for a developer", "Allow quick access to background tasks through the UI"},
            {"To handle data such as databases", "To prevent unwanted access to hidden information"},
            {"Provides a developer with tools to implement external media", "Responds to requests from other applications"},
            {"Layouts designed for different device types", "The pixel density of a layout"},
            {"Chunks of a layout that are separated by constraints", "A layout within a layout"},
            {"A data filled file for saving data", "A database holding type"},
            {"Broadcasts data which is then received by another activity", "Listens for external data from outside of the application."}
    };

    //Third array holds all possible answers for questions in Topic 3
    private String mChoices3[][] = {

            {"Stores libraries for java", "Is a nickname for coffee"},
            {"Has the compiled .gradle files", "Contain information about the layouts of the entire app"},
            {"Runs the first activity of the app", "Builds all the required SDKs"},
            {"Setups the use of character arrays", "Let’s you place words inside java files"},
            {"Used to make arrays storing files", "A file referenced by the MainActivity to display only video and images."},
            {"Res/layout", "Res/drawable-hdpi"},
            {"Res/value ", "Res/drawable-hdpi"},
            {"Res/layout", "Res/value "},
            {"•To temporarily hold text for storage", "A way to place text inside Java files"},
            {"Let’s you type strings into TextViews", "Store values as a string"}
    };

    //Fourth array holds all possible answers for questions in Topic 4
    private String mChoices4[][] = {

            {"Image files that hold .png, .jpg and .gif", "XML files that define user interface"},
            {"XML files that define animations ", "XML files that define user interface"},
            {"XML files that define animations ", "Image files that hold .png, .jpg and .gif"},
            {"XML files that define animations ", "Image files that hold .png, .jpg and .gif"},
            {"To enhance the file size of the project", "To allow better viewing when developing on PC"},
            {"Code", "XML"},
            {"A file holding all debugging information", "It contains resource information for only array structures"},
            {"A folder that contains all mathematic equations", "Stores user input values for later use"},
            {"XML that holds character only arrays", "XML that holds only integer arrays"},
            {"XML for styles on individual activities", "XML for styles on coding pages"}
    };

    //Fifth array holds all possible answers for questions in Topic 5
    private String mChoices5[][] = {

            {"main()", "onStart()"},
            {"It is not an android callback", "Starts when the user interacts with the screen"},
            {"Called when the app freezes and needs to restart", "Called when the app resumes from an activity pausing"},
            {"4", "5"},
            {"Stops all processes including user input", "Stops a specific button from user input"},
            {"Callback that destroys the set button", "Callback to remove images and videos from memory"},
            {"Restarts an activity that has crashed", "Allows the user to reset a screen"},
            {"To let the system, know that the main activity is launchable by user input", "To let the system, know when the app can be closed and launched when minimising the main screen"},
            {"Sets the current display as the main screen", "Loads the current layout for the next activity"},
            {"Print an error message to the user", "Display all erroneous code and output to a file"}
    };


    //First array holds the answers to each question in Topic 1
    private String mAnswers1[] = {

            "Linux",
            "Google",
            "A & B",
            "Linux, Windows & Mac",
            "4",
            "android.opengl",
            "Davlik Virtual Machine",
            "Controls all aspects of the application lifestyle and activity stack",
            "Is used to store your created app",
            "3.6"
    };

    //Second array holds the answers to each question
    private String mAnswers2[] = {

            "Activities, Services, Broadcast Receivers & Content Providers",
            "4",
            "A single screen with a user interface that performs an action on screen",
            "Handle background processes associated with an application",
            "To perform long running operations",
            "Supplies data from one application to another on request",
            "UI elements that are drawn on screen",
            "Represents a portion of the user interface",
            "Configuration file for the app",
            "Broadcast Receivers respond to broadcast messages from other applications or from the system"
    };

    //Third array holds the answers to each question
    private String mAnswers3[] = {

            "Contains all your .java source files",
            "Works an interface between the Android OS and the application",
            "Is the actual application file",
            "Contains all text the application uses",
            "A file referenced by the app for building the interface",
            "Res/value",
            "Res/layout",
            "Res/drawable-hdpi",
            "To build text boxes for the GUI",
            "Refers to saved strings in the strings.xml file"
    };

    //Fourth array holds the answers to each question
    private String mAnswers4[] = {

            "XML files that define animations",
            "Image files that hold .png, .jpg and .gif",
            "XML files that define user interface",
            "XML file that defines a set list of colours",
            "To support different device configurations",
            "Both",
            "It contains resource IDs for all resources in your application",
            "A folder that holds XML files for simple values",
            "XML that holds arrays",
            "XML for styles on each activity"
    };

    //Fifth array holds the answers to each question
    private String mAnswers5[] = {

            "onCreate()",
            "It is a callback that is called when the activity becomes visible to the user",
            "Called when the user starts interacting with the application",
            "7",
            "Callback called when the activity is no longer visible",
            "Callback called before the activity is destroyed by the system",
            "Callback called when the activity restarts after stopping",
            "Because they set the specified activity as the main activity to load on system start",
            "Loads all the UI components for a specific activity",
            "Used to generate log messages to the debugging screen"
    };

    //Return question from the mQuestion array 1
    public String getQuestion1(int a, int b) {

        String question0 = "";
        if (a == 1) {
            question0 = mQuestions1[b];
        } else if (a == 2) {
            question0 = mQuestions2[b];
        } else if (a == 3) {
            question0 = mQuestions3[b];
        } else if (a == 4) {
            question0 = mQuestions4[b];
        } else if (a == 5) {
            question0 = mQuestions5[b];
        }
        return question0;
    }

    ;

    //Return the first item from the mChoices1 array

    /*************Method for getting items out of the array*******************/
    public String getChoices1(int a, int b) {

        String choice0 = "";
        if (a == 1) {
            choice0 = mChoices1[b][0];
        } else if (a == 2) {
            choice0 = mChoices2[b][0];
        } else if (a == 3) {
            choice0 = mChoices3[b][0];
        } else if (a == 4) {
            choice0 = mChoices4[b][0];
        } else if (a == 5) {
            choice0 = mChoices5[b][0];
        }
        return choice0;
    }

    ;

    public String getChoices2(int a, int b) {

        String choice0 = "";
        if (a == 1) {
            choice0 = mChoices1[b][1];
        } else if (a == 2) {
            choice0 = mChoices2[b][1];
        } else if (a == 3) {
            choice0 = mChoices3[b][1];
        } else if (a == 4) {
            choice0 = mChoices4[b][1];
        } else if (a == 5) {
            choice0 = mChoices5[b][1];
        }
        return choice0;
    }

    ;

    /*************Method for getting items out of the array*******************/


    //Return correct answer for topic 1
    public String getAnswer1(int a, int b) {

        String answer0 = "";
        if (a == 1) {
            answer0 = mAnswers1[b];
        } else if (a == 2) {
            answer0 = mAnswers2[b];
        } else if (a == 3) {
            answer0 = mAnswers3[b];
        } else if (a == 4) {
            answer0 = mAnswers4[b];
        } else if (a == 5) {
            answer0 = mAnswers5[b];
        }
        return answer0;
    }

    ;
}
